# Tomcat
server:
  port: 9090
  
# Data Source
spring:
  datasource:
    url: jdbc:postgresql://postgresql.yooyu-family.cn:19793/yooyu-webapp
    username: postgres
    password: Pass1234
    driver-class-name: org.postgresql.Driver
  redis:
    database: 0
    host: redis.yooyu-family.cn
    port: 19637
    password: 
    pool: 
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 8 # 连接池中的最大空闲连接
      min-idle: 0 # 连接池中的最小空闲连接
      timeout: 0 # 连接超时时间（毫秒）

logging:
  config: classpath:log4j2.xml

#AWS
aws:
  account:
    accessKeyId: AKIAIAUESC2O43NSEWJQ
    secretAccessKey: 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
  bucket:
    region: ap-southeast-1 #新加坡
    pic: aws-yooyu-pic-ap-southeast-1-021670840239
    video: aws-yooyu-webapp-video

# app
app:
  id: yooyu-webapp


