# Tomcat
server:
  port: 9090
  
# Data Source
spring:
  datasource:
    url: jdbc:postgresql://yooyu-webapp.clba9qy07yro.us-east-1.rds.amazonaws.com:5432/postgres
    username: root
    password: swwswj384900
    driver-class-name: org.postgresql.Driver

logging:
  config: classpath:log4j2.xml

aws:
  account:
    accessKeyId: AKIAIAUESC2O43NSEWJQ
    secretAccessKey: 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
  bucket:
    pic: aws-yooyu-pic-us-east-1-021670840239
    video: aws-yooyu-webapp-video
