# Tomcat
server:
  port: 9090
  
# Data Source
spring:
  datasource:
    url: jdbc:postgresql://yooyu-webapp.clba9qy07yro.us-east-1.rds.amazonaws.com:5432/yooyu_webapp
    username: root
    password: swwswj384900
    driver-class-name: org.postgresql.Driver
  # redis:
  #   database: yooyu-redis-0001-001 # Redis数据库索引（默认为yooyu-redis-0001-001）
  #   host: yooyu-redis.j1eptx.clustercfg.use1.cache.amazonaws.com
  #   # database: 0
  #   # host: localhost
  #   port: 6379
  #   password: 
  #   pool: 
  #     max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
  #     max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  #     max-idle: 8 # 连接池中的最大空闲连接
  #     min-idle: 0 # 连接池中的最小空闲连接
  #     timeout: 0 # 连接超时时间（毫秒）

logging:
  config: classpath:log4j2.xml

#AWS
aws:
  account:
    accessKeyId: AKIAIAUESC2O43NSEWJQ
    secretAccessKey: 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
  bucket:
    region: us-east-1
    pic: aws-yooyu-pic-us-east-1-021670840239
    video: aws-yooyu-webapp-video

# app
app:
  id: yooyu-webapp


