aws:
  account:
    accessKeyId: AKIAIAUESC2O43NSEWJQ
    secretAccessKey: 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
  bucket:
    pic: aws-yooyu-pic-us-east-1-021670840239
    video: aws-yooyu-webapp-video